### ISSUE TITLE
deckem build error

### ISSUE THREAD

**Issue by generalhenry** [DamonOehlman/deckem#1]
node v0.4.11

unchanged deckem create main.jade

deckem build returns

/usr/local/lib/node_modules/deckem/bin/deckem:22
        action.call(builder, program, function() {
         ^
TypeError: Cannot call method 'call' of undefined
    at [object Object].<anonymous> (/usr/local/lib/node_modules/deckem/bin/deckem:22:10)
    at [object Object].emit (events.js:61:17)
    at /usr/local/lib/node_modules/deckem/lib/deckem.js:21:17
    at /usr/local/lib/node_modules/deckem/lib/deckem.js:45:13

**Comment by DamonOehlman** [comment]
Thanks - I'll have a look into this...

**Comment by generalhenry** [comment]
/usr/local/lib/node_modules/deckem/lib/actions/build.js is missing when I npm install

**Comment by generalhenry** [comment]
I copied build.js into place at it works, seems to be an issue with the npm install

**Comment by DamonOehlman** [comment]
I know why this is - will fix...

**Comment by DamonOehlman** [comment]
I've updated the `.npmignore` file to be more specified with regards to build.js (which exists in the root directory for compiling the deckem.css and deckem.js files).  I'll bump the version and push to npm again soon, although I want to change `main.jade` to `deck.jade` and creating `index.html` instead of `main.html` too as I think it makes more sense...

**Comment by DamonOehlman** [comment]
Could you try uninstalling and reinstalling the npm package.  I've bumped the version and published to NPM.  From my own testing here it looks like build.js is included correctly now.

Thanks,
Damon.

**Comment by generalhenry** [comment]
~/deck# npm uninstall deckem -g
~/deck# deckem build
-bash: /usr/local/bin/deckem: No such file or directory
~/deck# npm install deckem -g
/usr/local/bin/deckem -> /usr/local/lib/node_modules/deckem/bin/deckem
deckem@0.0.3 /usr/local/lib/node_modules/deckem 
├── commander@0.1.0
├── out@0.0.1
├── ncp@0.1.2
└── jade@0.15.4
~/deck# deckem build

/usr/local/lib/node_modules/deckem/bin/deckem:22
        action.call(builder, program, function() {
         ^
TypeError: Cannot call method 'call' of undefined
    at [object Object].<anonymous> (/usr/local/lib/node_modules/deckem/bin/deckem:22:10)
    at [object Object].emit (events.js:61:17)
    at /usr/local/lib/node_modules/deckem/lib/deckem.js:21:17
    at /usr/local/lib/node_modules/deckem/lib/deckem.js:45:13
~/deck# 

Still having the issue.

**Comment by DamonOehlman** [comment]
OK - I've completely removed any reference to build.js from `.npmignore` and republished to NPM.  If you could try one last time, I'd appreciate it :)

Thanks again,
Damon.

**Comment by generalhenry** [comment]
~/deck# npm install deckem -g
/usr/local/bin/deckem -> /usr/local/lib/node_modules/deckem/bin/deckem
deckem@0.0.3 /usr/local/lib/node_modules/deckem 
├── commander@0.1.0
├── out@0.0.1
├── ncp@0.1.2
└── jade@0.15.4
~/deck# deckem build
Template loaded from: !{underline}/usr/local/lib/node_modules/deckem/assets/templates/default

^__^

fixed

**Comment by DamonOehlman** [comment]
Hooray! Although it does look like one of my other NPM (out) libraries isn't behaving as it should.

That, however, is another story...

If you have any feedback / requests the definitely let me know :)
